---
title: "Session 1 - Pivoting"
output: word_document
date: "2025-03-16"
---

```{r setup}
#| include: FALSE
knitr::opts_chunk$set(echo = TRUE)

for(packageName in c(#"devtools",            # R packages needed here
                     "here",
                     "magrittr",
                     #"NlinTS",
                     #"nonlinearAnalysis",
                     #"rEDM",
                     #"Rssa",
                     "tidyverse")) {
  if(!is.element(packageName,               # If package is NOT installed...
                 installed.packages()[,1])) {
    install.packages(packageName)           #  ...then install it.
  }
  library(packageName,                      # Add package to environment
          character.only=TRUE,
          quietly=TRUE,
          verbose=FALSE)
}

i_am("Scripts/Session 1 - Pivoting.Rmd") # To help find all the files.

options(show.signif.stars = FALSE)          # Don't stargaze
options(digits = 3)                         # Round to 3 digits by default
```

```{r data}
read.csv(here("Data/Pivot1.csv")) ->
  df1

read.csv(here("Data/Pivot2.csv")) ->
  df2

```

# Basic Pivot

```{r}
vignette("pivot")
```

# Two step

```{r}
df2 %>%                                     # Two steps
  pivot_longer(                             # One column for each wave (7 total)
    cols = -PARENTID,
    names_to = c(".value", "Measure"),
    names_sep = "_",
    values_drop_na = FALSE
  ) ->
  temp_df 

temp_df %>%
  pivot_longer(                              # Collapse wave columns into one
    cols = -c(PARENTID, Measure),
    names_to = "Wave",
    names_transform = readr::parse_number,
    values_to = "Value",
    values_drop_na = FALSE
  ) -> 
  df2_long_df                               # long df

```

# Multiple Questions from Multiple Scales on Multiple Days

```{r}
df1 %>%
    pivot_longer(
    cols = -ID,
    cols_vary = "slowest",
    names_to = c(".value", 
                 "question", 
                 "time"),
    names_pattern = "(.*)_(.*).Day_(.*)",
    names_transform = 
      list(time = as.integer))  ->
  df1_long
```


